### ISSUE TITLE
Contribute your ideas in this repo 

### ISSUE THREAD

**Issue by developer-gerejaku** [Gerejaku/apps-opinion#1]
If you first timer or someone want to share your ideas , plus 😄  you want to completed hacktoberfest event . This repo is great idea to start .

**Comment by fgiuliani** [comment]
@developer-gerejaku how should the ideas be shared? A new file? A change in README?

**Comment by developer-gerejaku** [comment]
> @developer-gerejaku how should the ideas be shared? A new file? A change in README?

[Edited]
Just create a new file inside ideas directory , thanks

**Comment by fgiuliani** [comment]
@developer-gerejaku great! I'll create the PR in October, to completed Hacktoberfest event. Thanks!

**Comment by developer-gerejaku** [comment]
> @developer-gerejaku great! I'll create the PR in October, to completed Hacktoberfest event. Thanks!

Awesome much appreciated 😄  , don't forget to clone master branch .

**Comment by dolonmandal** [comment]
Can I  work on this as a part of hacktober fest 2020?

**Comment by kratikaatgithub** [comment]
Hi @developer-gerejaku  can you also assign this issue to me? I would like to work on this as part of hacktoberfest 2020.
Thanks

**Comment by Maxxoto** [comment]
> Can I  work on this as a part of hacktober fest 2020?

Sure , feel free to make a PR

**Comment by Priyanshu2802** [comment]
@developer-gerejaku THANKS BUDDY FOR YOUR SUPPORT

**Comment by sagarr70** [comment]
hello can you please assign this to me . it will help me complete hacktoberfest 2020

**Comment by developer-gerejaku** [comment]
> Can I work on this as a part of hacktober fest 2020?

Sure , feel free to make PR

**Comment by developer-gerejaku** [comment]
> hello can you please assign this to me . it will help me complete hacktoberfest 2020

Its public 😃  , feel free to fork it and make a PR . Thanks you

**Comment by developer-gerejaku** [comment]
> Hi @developer-gerejaku can you also assign this issue to me? I would like to work on this as part of hacktoberfest 2020.
> Thanks

Awesome @kratikaatgithub  , feel free to make PR  😉 .

**Comment by syarifuddinahmads** [comment]
I'm new to open source, can I join to contribute? :P

**Comment by developer-gerejaku** [comment]
@syarifuddinahmads Surely, thank you for your contribution . We're happy to wait your PR .
